services:
  # SERVICIO WEB (NGINX)
  web:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # SERVICIO PHP (PHP-FPM)
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm-server
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  # SERVICIO BASE DE DATOS (MYSQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: viajego_usuarios
      MYSQL_USER: user_docker
      MYSQL_PASSWORD: password_segura
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # <--- NUEVA LÃNEA CLAVE
    ports:
      - "3306:3306"

volumes:
  db-data: